import { Injectable, OnModuleInit } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';
import { createLogger } from '../../common/services/logger.service';
import { securityLogPath } from '../../common/security/security-event-log.service';
import { FAIL2BAN_DEFAULTS } from './config-sections';

/**
 * The two `failregex` patterns fail2ban uses to recognise an OpenWA security-event line. They are
 * written against EXACTLY the shape `formatSecurityLine` (in security-event-log.service.ts) emits —
 * `fail2ban-config.service.spec.ts` generates a real line from that function and asserts each pattern
 * matches and captures the IP, so a format/regex drift that would silently stop bans fails the build.
 *
 * `<HOST>` is fail2ban's own IP-capture token; the leading `.*` swallows whatever precedes the tag
 * (fail2ban strips the ISO-8601 timestamp via its date detection, but tolerating a remnant is safe).
 */
export const FAILREGEX_WRONG_API_KEY =
  '^.*OPENWA-SECURITY v=1 event=block reason=wrong_api_key surface=\\S+ ip=<HOST>\\s*$';
export const FAILREGEX_INVALID_REQUEST =
  '^.*OPENWA-SECURITY v=1 event=block reason=invalid_request surface=\\S+ ip=<HOST>\\s*$';

export interface Fail2banSettings {
  enabled: boolean;
  maxretry: number;
  findtime: number;
  bantime: number;
}

/**
 * Resolve the effective fail2ban settings. `source` (the merged env map the save path just wrote) is
 * preferred so a regenerate triggered by a save reflects the NEW values before they reach
 * `process.env`; at boot `source` is omitted and the loaded env is read. A positive-integer clamp
 * mirrors env.validation so a blank/garbage value falls back to the default rather than a broken jail.
 */
export function resolveFail2banSettings(source?: Record<string, string | undefined>): Fail2banSettings {
  const read = (key: string): string | undefined => (source ? source[key] : process.env[key]);
  const posInt = (raw: string | undefined, fallback: number): number => {
    const trimmed = raw?.trim();
    const n = trimmed && /^\d+$/.test(trimmed) ? Number(trimmed) : NaN;
    return Number.isInteger(n) && n >= 1 ? n : fallback;
  };
  return {
    enabled: (read('FAIL2BAN_ENABLED') ?? '').trim() === 'true',
    maxretry: posInt(read('FAIL2BAN_MAXRETRY'), FAIL2BAN_DEFAULTS.maxretry),
    findtime: posInt(read('FAIL2BAN_FINDTIME'), FAIL2BAN_DEFAULTS.findtime),
    bantime: posInt(read('FAIL2BAN_BANTIME'), FAIL2BAN_DEFAULTS.bantime),
  };
}

/** The fail2ban filter definition (`filter.d/openwa.conf`) — the two failregex, no ignoreregex. */
export function buildFilterFile(): string {
  return [
    '# OpenWA fail2ban filter — GENERATED by Dashboard > Infrastructure. Do not edit by hand.',
    '# Recognises the security-event lines OpenWA writes to its dedicated security log.',
    '[Definition]',
    `failregex = ${FAILREGEX_WRONG_API_KEY}`,
    `            ${FAILREGEX_INVALID_REQUEST}`,
    'ignoreregex =',
    '',
  ].join('\n');
}

/**
 * The fail2ban jail (`jail.d/openwa.local`) for the `openwa` filter. `banaction` is the all-ports
 * iptables action with `blocktype=DROP` so a banned IP's packets are silently discarded (a DROP, per
 * the operator request) rather than actively refused; the host docs cover the nftables equivalent.
 */
export function buildJailFile(settings: Fail2banSettings, logpath: string): string {
  return [
    '# OpenWA fail2ban jail — GENERATED by Dashboard > Infrastructure. Do not edit by hand.',
    '[openwa]',
    `enabled  = ${settings.enabled ? 'true' : 'false'}`,
    'filter   = openwa',
    `logpath  = ${logpath}`,
    `maxretry = ${settings.maxretry}`,
    `findtime = ${settings.findtime}`,
    `bantime  = ${settings.bantime}`,
    '# DROP (silently discard) all ports, not REJECT. nftables hosts: nftables-allports[blocktype=drop].',
    'banaction = iptables-allports[blocktype=DROP]',
    '',
  ].join('\n');
}

/**
 * Generates the host-side fail2ban filter + jail files from the dashboard settings. The app is
 * unprivileged and CANNOT run fail2ban or touch the host firewall (see docs/31-fail2ban.md): it only
 * writes these config files onto the shared data volume, where a host-side fail2ban include picks them
 * up. Regeneration runs at boot (so the files exist without a dashboard save) and after every
 * Infrastructure save (so a settings change is reflected immediately). Best-effort: a write failure is
 * logged, never thrown — it must not break boot or a config save.
 */
@Injectable()
export class Fail2banConfigService implements OnModuleInit {
  private readonly logger = createLogger('Fail2banConfigService');

  static baseDir(): string {
    return path.resolve(process.cwd(), 'data', 'fail2ban');
  }
  static filterPath(): string {
    return path.join(Fail2banConfigService.baseDir(), 'filter.d', 'openwa.conf');
  }
  static jailPath(): string {
    return path.join(Fail2banConfigService.baseDir(), 'jail.d', 'openwa.local');
  }
  /** Host-produced (fail2ban-client → JSON). The app only READS this; it never writes it. */
  static statusPath(): string {
    return path.join(Fail2banConfigService.baseDir(), 'status.json');
  }

  onModuleInit(): void {
    // Regenerate at boot so filter.d/jail.d exist even on a stack that never saved from the dashboard.
    this.regenerate();
  }

  regenerate(source?: Record<string, string | undefined>): void {
    const settings = resolveFail2banSettings(source);
    try {
      const filterPath = Fail2banConfigService.filterPath();
      const jailPath = Fail2banConfigService.jailPath();
      fs.mkdirSync(path.dirname(filterPath), { recursive: true });
      fs.mkdirSync(path.dirname(jailPath), { recursive: true });
      // 0644 (plain, NOT writeSecretFile): these are non-secret config the host fail2ban must read.
      fs.writeFileSync(filterPath, buildFilterFile(), { mode: 0o644 });
      fs.writeFileSync(jailPath, buildJailFile(settings, securityLogPath()), { mode: 0o644 });
      this.logger.log('fail2ban config regenerated', { enabled: settings.enabled });
    } catch (err) {
      this.logger.warn('Could not write fail2ban config (host fail2ban will use the last generated files)', {
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }
}
